# Generated by Django 4.0.5 on 2022-06-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_show_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['date', 'time']},
        ),
    ]
